### ISSUE TITLE
Sending messages over slack results in a PM from self on IRC

### ISSUE THREAD

**Issue by gpl** [insomniacslk/irc-slack#100]
Found another interesting bug --

Appears to be implemented properly for channels, but seems to be broken on PMs.

Reproduction steps: 

1) Send message on the official slack client to another user JohnDoe over PM
2) receive message on the buffer labeled with your slack username as opposed to the buffer w/ user JohnDoe

Here's what I pulled from tcpdump -- (although I think this is correct?  Might be a quassel issue on my end.)
<slack.username>!<slack.id>@10.9.2.201 PRIVMSG JohnDoe :asdfasdfa asdfasdfas asdfasdf asdfasdfa

**Comment by gpl** [comment]
Ah, this is definitely a quassel issue.  Was unable to reproduce the behavior on other clients.

**Comment by insomniacslk** [comment]
No worries! If the issue only shows up on Quassel we can see if there's a workaround until the bug (if any) is fixed on their side
