### ISSUE TITLE
Use slacks 'away' flag when loading slack users

### ISSUE THREAD

**Issue by chex3** [insomniacslk/irc-slack#127]
I am having an issue with irc-slack when connecting to public, highly trafficked slacks with lots of users, who are now inactive on the slack.  Thousands of mostly inactive users create memory usage in the app which is excessive on the small VPS server I run this app on. 

Slack seems to have a concept of an 'away' slack user when they have been away/logged out of the slack for an extended time. 

Is there a way to set a flag to have irc-slack connect and use a list of slack users who are not away? 

It might make the loading of thousands of slack users a lot less if this flag could be set. 

Thank you, Stefan S

**Comment by insomniacslk** [comment]
One way could be to only store users that are not away, but since this may not be desirable for everyone, it could go behind a command-line flag.

Another option is to profile the application and see what of those ~10kb/user could be shaved off.
I'll give it a look during next week. Thanks for reporting it!

**Comment by chex3** [comment]
To be clear, this 'away' flag seems to be something set for users who have been inactive/logged-out of the slack for a long time, not something user-set for if someone is logged in to the slack and are manually setting that are 'away' in the IRC sense.  
EDIT: Nope, I am incorrect. A user can set themselves as being 'away' on the user-profile dock, but I wonder how many people actually use this feature.  Slack seems to be auto-setting this if a user is logged out for a long time ( months.. ) 

More investigation is needed to see how this works on Slack.

**Comment by insomniacslk** [comment]
This should also be indirectly addressed by https://github.com/insomniacslk/irc-slack/pull/132

**Comment by insomniacslk** [comment]
Closing this as the underlying issue is addressed by faster loading, feel free to reopen if needed
