### ISSUE TITLE
My own messages are shown twice

### ISSUE THREAD

**Issue by ngortheone** [insomniacslk/irc-slack#128]
Hi. First off thanks for the great app!

I use Quassel IRC and when I send a message a split second later the same message appears again. As if I sent it twice.

Others do not see doubled messages, even I don't see it in native slack client. So it is probably something between Quassel and irc-slack that makes Qassel show my own message 2 times.

**Comment by chex3** [comment]
I have this issue, with irssi, also. 

- Stefan

**Comment by ajgon** [comment]
Same problem with thelounge.

**Comment by janza** [comment]
Hi, are you using Slack App token or legacy tokens for authentication with slack?

**Comment by insomniacslk** [comment]
Now I'm seeing this too, using a refreshed token/cookie on an MFA-enabled account. @ngortheone @chex3 @ajgon are you still seeing this? And as Josip was also asking, which type of token are you using?

**Comment by insomniacslk** [comment]
Btw I plan to fix this over the weekend

**Comment by insomniacslk** [comment]
quick repro: this happens only with token+cookie, not with legacy tokens

**Comment by chex3** [comment]
Hi, I am definitely still seeing this issue, and yes, I use token+cookie. 

- Stefan

example: 

11:10:58    chex38 | woo hooo
11:10:59 U0SN7DR1S | woo hooo
11:11:07    chex38 | do you see messages double??
11:11:08 U0SN7DR1S | do you see messages double??

**Comment by insomniacslk** [comment]
The reason is that Slack sends an event with your own message when using the new style tokens.

This should be fixed in https://github.com/insomniacslk/irc-slack/pull/135 . Can people on this thread test it too before we merge it?
