### ISSUE TITLE
App on slack.efi.re throws 502 error

### ISSUE THREAD

**Issue by janza** [insomniacslk/irc-slack#136]
I was trying to get the app token but the hosted application seems to be down.

**Comment by insomniacslk** [comment]
I developed the app before developing `autotoken`, which is way better, so I disabled it. Do you think it's still valuable to have?

**Comment by insomniacslk** [comment]
the downside of the app is that people have to trust it to be non-malicious, and I'd rather have them not trust anyone, including my own hosted app (reason why I shared the source code under `tools/`)

**Comment by janza** [comment]
Oh, I missed the part about authentication using user tokens in README. Seems like hosting the app is not needed indeed, but would be good to remove it from the README.
