### ISSUE TITLE
Messages posted to threads show up in 1-on-1 channels

### ISSUE THREAD

**Issue by gjabell** [insomniacslk/irc-slack#153]
Thanks for this project, makes slack much nicer to use than with their web UI :)

It seems that if someone responds to a thread while there is also a 1-on-1 chat open for that same user (for example from /QUERY), then the message they posted to the thread will appear in the 1-on-1 chat rather than under the thread. Note that the thread "channel" still opens, but the messages aren't posted to it.

Can provide debug logs or testing as needed.

**Comment by insomniacslk** [comment]
Hey @gjabell , thanks for your feedback!
I have tried to reproduce the bug without luck, please help me understand if I did the right thing:
* created a private chat with a friend
* asked my friend to reply me on a thread on another channel
* verify that that the thread reply appears on the thread channel rather than the 1:1 chat

After doing so, I got my friend's reply on the thread channel as expected instead of the 1:1 chat as you experienced.

If this is the correct repro for the issue, can you please tell me which commit hash did you build `irc-slack` from? And attach the relevant part of your logs when running with `-D` (please remove any sensitive information before attaching it)

**Comment by gjabell** [comment]
Thanks for the quick response! Yes that should be the reproduction steps; it seems it is also an issue if there is not already an open chat with the user, ie anything sent in the thread channel appears instead under the private chat that automatically opens.

Here are the relevant debug logs (hopefully removed any private info):
```
time="2021-01-20T12:09:58+01:00" level=info msg="Incoming Event: {"type":"message","subtype":"message_replied","hidden":true,"message":{"type":"message","text":"","user":"USER1","ts":"1611140246.011400","team":"TE079222U","thread_ts":"1611140246.011400","reply_count":3,"reply_users_count":2,"latest_reply":"1611140998.011900","reply_users":["USER2","USER1"]},"channel":"G0110L5TQTE","event_ts":"1611140998.012000","ts":"1611140998.012000"}
" prefix=slack-api
time="2021-01-20T12:09:58+01:00" level=info msg="Incoming Event: {"client_msg_id":"","suppress_notification":false,"type":"message","text":"Thanks :slightly_smiling_face:","user":"USER2","team":"TE079222U","blocks":[{"type":"rich_text","block_id":"1Qfpw","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Thanks "},{"type":"emoji","name":"slightly_smiling_face"}]}]}],"thread_ts":"1611140246.011400","source_team":"","user_team":"","channel":"G0110L5TQTE","event_ts":"1611140998.011900","ts":"1611140998.011900"}" prefix=slack-api
time="2021-01-20T12:09:59+01:00" level=info msg="Incoming Event: {"type":"update_thread_state","has_unreads":true,"mention_count":17,"mention_count_by_channel":{"G019DC85D8A":1,"G016G979WAH":1,"G0125AXQ06P":1,"CFBH47NUV":1,"D01906L67V5":6,"G0110L5TQTE":1,"D0111EBMQ82":5,"D0121UNSLSW":1},"timestamp":"1611140999.309503","unread_count_by_channel":{"G0110L5TQTE":16,"D0111EBMQ82":4,"CE211M7U7":5,"D01906L67V5":6,"CFBH47NUV":3,"D0121UNSLSW":1,"G016G979WAH":5,"D01263L1ZPT":1,"G0125AXQ06P":1,"G019DC85D8A":1},"event_ts":"1611140999.088000"}" prefix=slack-api
time="2021-01-20T12:09:59+01:00" level=info msg="RTM Error - received unmapped event "update_thread_state": {"type":"update_thread_state","has_unreads":true,"mention_count":17,"mention_count_by_channel":{"G019DC85D8A":1,"G016G979WAH":1,"G0125AXQ06P":1,"CFBH47NUV":1,"D01906L67V5":6,"G0110L5TQTE":1,"D0111EBMQ82":5,"D0121UNSLSW":1},"timestamp":"1611140999.309503","unread_count_by_channel":{"G0110L5TQTE":16,"D0111EBMQ82":4,"CE211M7U7":5,"D01906L67V5":6,"CFBH47NUV":3,"D0121UNSLSW":1,"G016G979WAH":5,"D01263L1ZPT":1,"G0125AXQ06P":1,"G019DC85D8A":1},"event_ts":"1611140999.088000"}" prefix=slack-api
```

Also worth noting that I am using Weechat, so this might be a client-specific bug.

**Comment by insomniacslk** [comment]
Can you help me reproduce this together? Are you on the Gophers slack by any chance?

**Comment by gjabell** [comment]
@insomniacslk I'd be happy to; I'm not on the Gophers slack but I can join if it's open-registration.

**Comment by insomniacslk** [comment]
Yes, it's open, this should let you get an invite, https://invite.slack.golangbridge.org/

**Comment by insomniacslk** [comment]
Should be fixed by https://github.com/insomniacslk/irc-slack/pull/165

**Comment by insomniacslk** [comment]
waiting on @gjabell to confirm before closing this :)

**Comment by gjabell** [comment]
Seems to work correctly for me now, thanks for all the support!
