### ISSUE TITLE
High memory pressure

### ISSUE THREAD

**Issue by insomniacslk** [insomniacslk/irc-slack#40]
`irc-slack` uses too much memory. Without any connection it takes around 1MB RSS, but a large Slack team (thousands of people) that I'm testing on is taking 200 MB RSS.
Furthermore, upon disconnection it does not release the used memory.

**Comment by chex3** [comment]
Hello: 

Thank you for opening this bug.  I am on the one having this issue, with a Slack named NetToCode.  When I just connect to that one slack, the paging of the users in each channel scrolls a lot, and the RSS memory usage quickly goes 1000 MB, and then crashes, because that server only has 1GB of RAM. 

- Stefan

**Comment by insomniacslk** [comment]
hey @chex3 :) I'm catching up with these issues now. I am testing it on two heavy slack teams (networktocode and u-root) and the RSS seems to stabilize around 40MB. Can you please re-test this on your side and let me know? I think this was a memory leak fixed by #79

**Comment by insomniacslk** [comment]
Right now using this to measure RSS every 30 seconds:
```
while true; do sudo pmap -x $(pgrep irc-slack) | awk '/^total/ {print $4}'; sleep 30; done
```

**Comment by insomniacslk** [comment]
I also notice that on reconnections the memory goes up again - slightly, but up.  This is a different issue but worth tracking here

**Comment by insomniacslk** [comment]
So, the old memory leak was fixed months ago. At least the memory usage doesn't climb anymore.

Just tried again on the NetworkToCode Slack team, it has ~14000 users, and it takes 154 MB of ram, as opposed to the ~1GB reported by @chex3 above. If the usage was naively linear, this would mean ~10kb of RAM per user. I think it's good enough to close this issue.
There are probably other ways to further optimize the memory usage, but this is not a priority at this time

**Comment by insomniacslk** [comment]
And also just verified that on gophers.slack.com (~50.000 users) it takes about 600MB of RSS, the numbers seem correct
