### ISSUE TITLE
Queries not showing up in chat lists.

### ISSUE THREAD

**Issue by alexfornuto** [insomniacslk/irc-slack#52]
First of all, thanks for the project!

When I connect to my IRC gateway using Quassel, queries don't show up in my chat list, only rooms. I haven't yet tried with other clients, but will try to do so.

**Comment by insomniacslk** [comment]
Hey @alexfornuto , thanks for reporting this :) Would you be able to test it with a different client first? I am using weechat and irssi as reference clients, and queries work fine. If it's a Quassel-specific issue we can then debug it together. Thanks!

**Comment by alexfornuto** [comment]
Unfortunately the admins of the Slack workspace I use revoked my token and forbade me from setting up an IRC bridge, so I won't be able to test that way.

If you have a test Slack workspace that you would like me to connect to to I could do some more A/B testing for the sake of the project, but if no one else is using Quassel and/or having this issue, I wouldn't be upset if you closed the issue.

**Comment by insomniacslk** [comment]
I can use another Slack team for the purpose. I need to install Quassel to properly test this issue, this will take a few days though. I wouldn't close the issue and leave Quassel's users locked out :)

**Comment by insomniacslk** [comment]
whoa, 300MB of dependencies! I should be able to test it today/tomorrow

**Comment by insomniacslk** [comment]
this made me notice that TOPIC is broken too

**Comment by insomniacslk** [comment]
TOPIC issue "fixed" in https://github.com/insomniacslk/irc-slack/commit/b9317eba3c7effbe42b1d03f9205685f660a26fa . Slack now uses Purpose, which is different from Topic, but what we want is the Purpose to be shown as IRC topic.

**Comment by insomniacslk** [comment]
I am testing this again today

**Comment by insomniacslk** [comment]
@alexfornuto I've tested it from Quassel and private messages work fine, probably fixed in some past commit. I'm closing this issue now but please reopen it if you feel this is not fixed yet. Thanks!
