### ISSUE TITLE
Supporting threads

### ISSUE THREAD

**Issue by janza** [insomniacslk/irc-slack#63]
Are there already any ideas of how threads could be supported in irc-slack? Eg: creating a new virtual irc channel per thread or something similar?

**Comment by insomniacslk** [comment]
Slack's threading interface is quite ugly in my opinion, and has several shortcomings. Your suggestion to use dedicated channels per thread is probably the one that better suits IRC, with only the risk is that we create a lot of channels on busy Slack teams. Still, it sounds the best trade-off.

Threads are documented here, https://api.slack.com/docs/message-threading , and to make things weirder they are identified by the first message's... timestamp (see https://api.slack.com/methods/channels.replies ). They can be created from public or private conversations, and the thread replies from a channel can either be sent to the channel, or stay private to the two participants. This is not easy to handle, and I am not sure what would be the saner default (reply privately? Or on the channel?).

Said that, whatever we do won't fit everybody and every case, so let's just try to have not-too-insane defaults here. I would start on what you suggest: creating a channel per thread. Then:
* the topic could reference to the conversation the thread was originated from
* the first message of the thread should be replicated in the thread-channel (which means that the original message should be retrieved by its timestamp when the first reply occurs)
* the channel name should be something like @thread-SOME_ID or similar, with a leading symbol that will avoid ambiguity with private and public channels, and multi-user conversations (we already use "@" for multi-user conversations, it's just an example)
* the reply would go to the channel (I assume this captures the majority of the use cases)

What do you think?

**Comment by janza** [comment]
Actualy one thing I noticed still missing is creating a threaded conversation from IRC. I can live without this feature, but might be interesting to implement for some users. 

Eg: a command where you can pass the number which represents the index of the message in a reverse chronological order. So if you want to reply to the last message you write: `/thread 1 my message is here`, for message sent before that `/thread 2 ...`, etc.

**Comment by insomniacslk** [comment]
I like it. This could be used to send other slack commands (even raw commands), and deserves its own issue
