### ISSUE TITLE
Remote user puppeteering on IRC?

### ISSUE THREAD

**Issue by poVoq** [insomniacslk/irc-slack#69]
https://github.com/qaisjp/go-discord-irc

Maybe something to integrate / replicate?

**Comment by insomniacslk** [comment]
I am not sure what the request is here, can you please expand?On 3 Sep 2019 13:44, poVoq <notifications@github.com> wrote:https://github.com/qaisjp/go-discord-irc
Maybe something to integrate / replicate?

**Comment by poVoq** [comment]
The bot bridge linked reads all the users on the Discord side and creates fake puppet users on the IRC side. So from IRC side it almost looks like the Discord users are real IRC participants and not just funneled through a single bot user.

**Comment by janza** [comment]
That is how this gateway currently behaves, in IRC you see usernames of slack users not a bot user, and in slack you see messages posted by the user who's token is used in the gateway configuration.

**Comment by insomniacslk** [comment]
closing this as this behaviour already exists, feel free to reopen for further discussion
