### ISSUE TITLE
Automate build creation

### ISSUE THREAD

**Issue by insomniacslk** [insomniacslk/irc-slack#7]
At every release, also automatically publish the artifacts. See https://docs.travis-ci.com/user/deployment/releases/

**Comment by marvinpinto** [comment]
Thank you creating this project, it will be very useful now that Slack has sunset their IRC gateway. :100: 

Couple questions:

1. Could you cut a new release with the latest commits?
1. Are you looking for help with automating releases & generating the binaries? (this issue)

**Comment by marvinpinto** [comment]
Awesome, thank you again for your work :smile:

**Comment by insomniacslk** [comment]
no worries, thank you for your feedback, and please keep reporting bugs :)

**Comment by insomniacslk** [comment]
I guess that with the docker integration this is not needed anymore, feel free to reopen if you think otherwise
