### ISSUE TITLE
User name in channel list with user id

### ISSUE THREAD

**Issue by shyim** [insomniacslk/irc-slack#70]
I see in channel list ids of the user

**Comment by shyim** [comment]
I had to reconnect. I guess the user cache is not ready

**Comment by insomniacslk** [comment]
thanks for reporting this! I'll have a look today

**Comment by insomniacslk** [comment]
so - I had noticed the same issue a while back, and restarting irc-slack helped. I assume this happens when a new user joins the slack team

**Comment by bougyman** [comment]
The user list (in irssi) in most of my channels shows the slack ID, not the users's name. Also it doesn't seem to honor 'display name' of the users. A few channels user lists (with the /names command) _do_ show their slack 'name' (not display name), but most show that U02938495 thing.

**Comment by insomniacslk** [comment]
can you please let me know if this is fixed for you? At the moment I can't reproduce it

**Comment by Poil** [comment]
On my side I have a lot of warn  ̀Could not fetch user UEQQTF955, not in user map`
Some user are resolved in a chan but not in another one.
It should be nice to cache the users information to be able to reuse them without querying the API at each re-connection

**Comment by insomniacslk** [comment]
work in progress in https://github.com/insomniacslk/irc-slack/pull/132

**Comment by insomniacslk** [comment]
@shyim @bougyman @Poil can you check that the latest commit (after https://github.com/insomniacslk/irc-slack/pull/132 ) fixes this for you?

**Comment by insomniacslk** [comment]
This should be fixed now - feel free to reopen if you still see the problem
