### ISSUE TITLE
Sending messages to self on slack creates PMs with message as username

### ISSUE THREAD

**Issue by gpl** [insomniacslk/irc-slack#85]
Found an odd bug:

When sending messages to yourself on the Slack web client, it results in the words you sent created as users.  To be more specific -- if you send the words `Hello World` to yourself on slack, a "user" `Hello World` sends an empty message.

![image](https://user-images.githubusercontent.com/39648069/71861016-abe8fa00-30a9-11ea-94c1-6a507b21f671.png)

Here's what I pulled from my logs.

localhost 400 <slack username> :Exactly two users expected in direct message, got 1 (conversation ID: \<removed\>)
\:\<slack username\>!\<slack user id\>@localhost PRIVMSG  :Hello World

**Comment by insomniacslk** [comment]
Hi @gpl, thanks for reporting this! This is because we explicitly discard conversations with a single user, see https://github.com/insomniacslk/irc-slack/blob/master/event_handler.go#L111 .

However this seems a legitimate, yet unusual, use case, so I'll make a patch soon

**Comment by insomniacslk** [comment]
@gpl the patch at https://github.com/insomniacslk/irc-slack/pull/86  seems to work for me. Can you please try it and let me know? Thanks!

**Comment by gpl** [comment]
Yep, patch works as expected, thanks!

**Comment by insomniacslk** [comment]
Thanks for checking!
