### ISSUE TITLE
Can this continue to function with the deprecation of legacy API tokens?

### ISSUE THREAD

**Issue by habys** [insomniacslk/irc-slack#94]
I don't really understand what "slack apps" can support.

**Comment by insomniacslk** [comment]
is there an announced deprecation date? If so, we need an alternative method

**Comment by habys** [comment]
https://api.slack.com/legacy/custom-integrations/legacy-tokens
reports:
This tool will not allow creation of new tokens beginning May 5th, 2020. Learn more about why you shouldn't use it anymore.

**Comment by insomniacslk** [comment]
If I understand correctly, the only option is to create a Slack App, and Slack Apps don't allow posting on behalf of the user

**Comment by janza** [comment]
If I'm reading the documentation correct it should still be possible to _impersonate_ the user with Apps: https://api.slack.com/messaging/sending#impersonation. We'd need to use _user token_ with the App https://api.slack.com/authentication/token-types#user

**Comment by insomniacslk** [comment]
yes it's possible with the approach you suggested, and if I understand correctly we need to write a small app with the appropriate permissions to retrieve the user token. I hope there's a simpler approach, but meanwhile I'm looking into what it takes to get such token with the right permissions

**Comment by insomniacslk** [comment]
In #99 I'm trying the Oauth token approach, please take a look

**Comment by insomniacslk** [comment]
I've merged #99. Needs more validation with the users who have trouble with that approach

**Comment by insomniacslk** [comment]
This is fixed by https://github.com/insomniacslk/irc-slack/pull/108

**Comment by insomniacslk** [comment]
I've merged #108, I think we are all set here and we can survive the legacy token shutdown
